- hosts: all
  tasks:
    # - name: Add Docker GPG apt Key
    #   apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     dest: /etc/apt/keyrings/docker.gpg
    #     state: present

    - name: Add keyrings folder 
      shell: mkdir -p /etc/apt/keyrings
      register: command_result
      ignore_errors: true

    - name: Add Docker GPG apt Key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      register: command_result


    - name: Register distribution *short* code name
      shell: lsb_release -cs
      register: lsb_release

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout | lower }} stable
        filename: /etc/apt/sources.list.d/docker.list 
        state: present

    - name: "apt-get update"
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true

    - name: "apt-get upgrade"
      apt:
        upgrade: dist
        force_apt_get: true

    - name: apt-get install docker-ce, docker-ce-cli, containerd.io and docker-compose-plugin
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin

    - name: Verify that Docker CE is installed correctly by running the hello-world image
      command: docker run --rm hello-world
      register: command_result
      failed_when: "'Hello from Docker!' not in command_result.stdout"

    - name: Add root user to docker group
      user:
        name: root
        groups: docker
        append: yes
