all:
  hosts:
    "37.27.7.160":
      hostname: "eh.dev1"
      ansible_ssh_user: "root"
      ansible_ssh_private_key_file: "/ansible/keys/key.openssh"
      ansible_port: 22
      IPv4: "192.168.100.2"
      IPv6: "2a01:4f9:c012:9b2a::/64"

    "95.216.203.205": #
      #CPU: AMD Ryzen 9 5950X 16-Core @ 32x 3.4GHz | 128 GB | raw: 6.99 TiB usable: 3.49 TiB
      hostname: "eh.dev2"
      ansible_ssh_user: "root"
      ansible_ssh_private_key_file: "/ansible/keys/key.openssh"
      ansible_port: 22
      IPv4: "192.168.100.3"
      IPv6: "2a01:4f9:c012:546f::/64"

    "135.181.42.70": #
      #CPU: AMD Ryzen 9 5950X 16-Core @ 32x 3.4GHz | 128 GB | raw: 6.99 TiB usable: 3.49 TiB
      hostname: "eh.dev3"
      ansible_ssh_user: "root"
      ansible_ssh_private_key_file: "/ansible/keys/key.openssh"
      ansible_port: 22
      IPv4: "192.168.100.4"
      IPv6: "2a01:4f9:c012:570b::/64"
  children:
    microk8s:
      hosts:
        "37.27.7.160":
        "95.216.203.205":
        "135.181.42.70":
    vswitch:
      hosts:
        "37.27.7.160":
        "95.216.203.205":
        "135.181.42.70":
