all:
  hosts:
    "95.216.203.205":
      hostname: "ehdev1"
      ansible_ssh_user: "root"
      ansible_ssh_private_key_file: "/ansible/keys/key.openssh"
      ansible_port: 22
      IPv4: "192.168.100.2"
      IPv6: "2a01:4f9:c012:546f::/64"

    "37.27.7.160":
      hostname: "ehdev2"
      ansible_ssh_user: "root"
      ansible_ssh_private_key_file: "/ansible/keys/key.openssh"
      ansible_port: 22
      IPv4: "192.168.100.3"
      IPv6: "2a01:4f9:c012:9b2a::/64"

    "135.181.42.70":
      hostname: "ehdev3"
      ansible_ssh_user: "root"
      ansible_ssh_private_key_file: "/ansible/keys/key.openssh"
      ansible_port: 22
      IPv4: "192.168.100.4"
      IPv6: "2a01:4f9:c012:570b::/64"
  children:
    microk8s:
      hosts:
        "95.216.203.205":
        "37.27.7.160":
        "135.181.42.70":
