all:
  hosts:
    "95.216.203.205":
      hostname: "eh.dev1"
      ansible_ssh_user: "root"
      ansible_ssh_private_key_file: "/ansible/keys/key.openssh"
      #ansible_port: 7777
      IPv4: "192.168.100.2"
      IPv6: "2a01:4f9:c012:546f::/64"

  children:
    microk8s:
      hosts:
        "95.216.203.205":
        #"213.239.198.153":
        #"46.4.29.56":
    vswitch:
      hosts:
        "95.216.203.205":
        #"213.239.198.153":
        #"46.4.29.56":
